# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            ''
tagline:          '2pegramming.site'
description:      '<a href="https://t.me/pepegramming" target="_blank">2pegramming</a>'
url:              http://pepegramming.site
baseurl:          '/'
future:           true

author:
  name:           'Anton Davydov'
  url:            https://pepegramming.site


# Custom vars
version:          2.1.0

github:
  repo:           http://github.com/2pegramming
